using System.Net;
using System.Text;

public static class HtmlGenerator
{
    private static readonly ItemType[] CategoryOrder =
    {
        ItemType.Weapon, ItemType.Armour, ItemType.Helmet,
        ItemType.Necklace, ItemType.Bracelet, ItemType.Ring,
        ItemType.Belt, ItemType.Boots,
        ItemType.Amulet, ItemType.Stone, ItemType.Torch,
        ItemType.Potion, ItemType.Ore, ItemType.Meat,
        ItemType.CraftingMaterial, ItemType.Scroll, ItemType.Gem,
        ItemType.Mount, ItemType.Book, ItemType.Script,
        ItemType.Reins, ItemType.Bells, ItemType.Saddle,
        ItemType.Ribbon, ItemType.Mask, ItemType.Food,
        ItemType.Hook, ItemType.Float, ItemType.Bait,
        ItemType.Finder, ItemType.Reel, ItemType.Fish,
        ItemType.Quest, ItemType.Awakening, ItemType.Pets,
        ItemType.Transform, ItemType.Deco, ItemType.Socket,
        ItemType.MonsterSpawn, ItemType.SiegeAmmo, ItemType.SealedHero
    };

    private static readonly HashSet<ItemType> EquipmentTypes = new()
    {
        ItemType.Weapon, ItemType.Armour, ItemType.Helmet,
        ItemType.Necklace, ItemType.Bracelet, ItemType.Ring,
        ItemType.Belt, ItemType.Boots
    };

    private static readonly HashSet<ItemType> ConsumableTypes = new()
    {
        ItemType.Potion, ItemType.Scroll, ItemType.Food, ItemType.Gem,
        ItemType.Ore, ItemType.Meat, ItemType.CraftingMaterial,
        ItemType.Amulet, ItemType.Bait, ItemType.Fish,
        ItemType.Awakening, ItemType.Socket, ItemType.SiegeAmmo,
        ItemType.SealedHero, ItemType.Transform
    };

    public static string Generate(List<ItemInfo> items, Dictionary<int, string> icons)
    {
        var grouped = items
            .GroupBy(i => i.Type)
            .ToDictionary(g => g.Key, g => g.OrderBy(i => i.Index).ToList());

        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine("<title>Item Wiki</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(GetCss());
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<h1>Item Wiki</h1>");

        // Navigation bar
        sb.AppendLine("<nav id=\"topnav\">");
        foreach (var type in CategoryOrder)
        {
            if (!grouped.ContainsKey(type) || grouped[type].Count == 0) continue;
            sb.AppendLine($"  <a href=\"#{type}\">{type} <span class=\"count\">({grouped[type].Count})</span></a>");
        }
        sb.AppendLine("</nav>");

        // Sections
        foreach (var type in CategoryOrder)
        {
            if (!grouped.ContainsKey(type) || grouped[type].Count == 0) continue;

            var typeItems = grouped[type];
            sb.AppendLine($"<section id=\"{type}\">");
            sb.AppendLine($"  <h2>{type} <span class=\"count\">({typeItems.Count})</span></h2>");
            sb.AppendLine("  <div class=\"table-wrap\">");

            if (EquipmentTypes.Contains(type))
                WriteEquipmentTable(sb, typeItems, icons);
            else if (ConsumableTypes.Contains(type))
                WriteConsumableTable(sb, typeItems, icons);
            else
                WriteOtherTable(sb, typeItems, icons);

            sb.AppendLine("  </div>");
            sb.AppendLine("</section>");
        }

        sb.AppendLine("<footer>Generated by ItemWikiGen</footer>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }

    private static void WriteEquipmentTable(StringBuilder sb, List<ItemInfo> items, Dictionary<int, string> icons)
    {
        sb.AppendLine("  <table>");
        sb.AppendLine("    <thead><tr>");
        sb.AppendLine("      <th>Icon</th><th>Name</th><th>Grade</th>");
        sb.AppendLine("      <th>DC</th><th>MC</th><th>SC</th><th>AC</th><th>MAC</th>");
        sb.AppendLine("      <th>HP</th><th>MP</th><th>Acc</th><th>Agi</th><th>Luck</th><th>AtkSpd</th>");
        sb.AppendLine("      <th>Dura</th><th>Req Lv</th><th>Class</th><th>Price</th>");
        sb.AppendLine("    </tr></thead>");
        sb.AppendLine("    <tbody>");

        foreach (var item in items)
        {
            string gradeClass = GetGradeClass(item.Grade);
            sb.AppendLine("    <tr>");
            sb.Append($"      <td class=\"icon-cell\">{IconImg(item.Image, icons)}</td>");
            sb.Append($"<td class=\"name {gradeClass}\">{Esc(item.Name)}</td>");
            sb.Append($"<td class=\"{gradeClass}\">{item.Grade}</td>");
            sb.Append($"<td>{FormatStatRange(item.Stats, Stat.MinDC, Stat.MaxDC)}</td>");
            sb.Append($"<td>{FormatStatRange(item.Stats, Stat.MinMC, Stat.MaxMC)}</td>");
            sb.Append($"<td>{FormatStatRange(item.Stats, Stat.MinSC, Stat.MaxSC)}</td>");
            sb.Append($"<td>{FormatStatRange(item.Stats, Stat.MinAC, Stat.MaxAC)}</td>");
            sb.Append($"<td>{FormatStatRange(item.Stats, Stat.MinMAC, Stat.MaxMAC)}</td>");
            sb.Append($"<td>{FormatStat(item.Stats, Stat.HP)}</td>");
            sb.Append($"<td>{FormatStat(item.Stats, Stat.MP)}</td>");
            sb.Append($"<td>{FormatStat(item.Stats, Stat.Accuracy)}</td>");
            sb.Append($"<td>{FormatStat(item.Stats, Stat.Agility)}</td>");
            sb.Append($"<td>{FormatStat(item.Stats, Stat.Luck)}</td>");
            sb.Append($"<td>{FormatStat(item.Stats, Stat.AttackSpeed)}</td>");
            sb.Append($"<td>{item.Durability}</td>");
            sb.Append($"<td>{FormatRequirement(item)}</td>");
            sb.Append($"<td>{FormatRequiredClass(item.RequiredClass)}</td>");
            sb.Append($"<td>{item.Price:N0}</td>");
            sb.AppendLine("</tr>");
        }

        sb.AppendLine("    </tbody>");
        sb.AppendLine("  </table>");
    }

    private static void WriteConsumableTable(StringBuilder sb, List<ItemInfo> items, Dictionary<int, string> icons)
    {
        sb.AppendLine("  <table>");
        sb.AppendLine("    <thead><tr>");
        sb.AppendLine("      <th>Icon</th><th>Name</th><th>Grade</th><th>StackSize</th><th>Weight</th><th>Price</th>");
        sb.AppendLine("    </tr></thead>");
        sb.AppendLine("    <tbody>");

        foreach (var item in items)
        {
            string gradeClass = GetGradeClass(item.Grade);
            sb.AppendLine("    <tr>");
            sb.Append($"      <td class=\"icon-cell\">{IconImg(item.Image, icons)}</td>");
            sb.Append($"<td class=\"name {gradeClass}\">{Esc(item.Name)}</td>");
            sb.Append($"<td class=\"{gradeClass}\">{item.Grade}</td>");
            sb.Append($"<td>{item.StackSize}</td>");
            sb.Append($"<td>{item.Weight}</td>");
            sb.Append($"<td>{item.Price:N0}</td>");
            sb.AppendLine("</tr>");
        }

        sb.AppendLine("    </tbody>");
        sb.AppendLine("  </table>");
    }

    private static void WriteOtherTable(StringBuilder sb, List<ItemInfo> items, Dictionary<int, string> icons)
    {
        sb.AppendLine("  <table>");
        sb.AppendLine("    <thead><tr>");
        sb.AppendLine("      <th>Icon</th><th>Name</th><th>Grade</th><th>Shape</th><th>Weight</th><th>Price</th>");
        sb.AppendLine("    </tr></thead>");
        sb.AppendLine("    <tbody>");

        foreach (var item in items)
        {
            string gradeClass = GetGradeClass(item.Grade);
            sb.AppendLine("    <tr>");
            sb.Append($"      <td class=\"icon-cell\">{IconImg(item.Image, icons)}</td>");
            sb.Append($"<td class=\"name {gradeClass}\">{Esc(item.Name)}</td>");
            sb.Append($"<td class=\"{gradeClass}\">{item.Grade}</td>");
            sb.Append($"<td>{item.Shape}</td>");
            sb.Append($"<td>{item.Weight}</td>");
            sb.Append($"<td>{item.Price:N0}</td>");
            sb.AppendLine("</tr>");
        }

        sb.AppendLine("    </tbody>");
        sb.AppendLine("  </table>");
    }

    private static string IconImg(int imageIndex, Dictionary<int, string> icons)
    {
        if (icons.TryGetValue(imageIndex, out string base64))
            return $"<img src=\"data:image/png;base64,{base64}\" class=\"item-icon\" />";
        return "<div class=\"no-icon\"></div>";
    }

    private static string FormatStatRange(Stats stats, Stat min, Stat max)
    {
        int lo = stats[min], hi = stats[max];
        if (lo == 0 && hi == 0) return "";
        return $"{lo}-{hi}";
    }

    private static string FormatStat(Stats stats, Stat stat)
    {
        int v = stats[stat];
        return v == 0 ? "" : v.ToString();
    }

    private static string FormatRequirement(ItemInfo item)
    {
        if (item.RequiredAmount == 0) return "";
        return item.RequiredType switch
        {
            RequiredType.Level => $"Lv {item.RequiredAmount}",
            RequiredType.MaxLevel => $"Lv ≤{item.RequiredAmount}",
            _ => $"{item.RequiredType} {item.RequiredAmount}"
        };
    }

    private static string FormatRequiredClass(RequiredClass rc)
    {
        if (rc == RequiredClass.None) return "All";
        var parts = new List<string>();
        if (rc.HasFlag(RequiredClass.Warrior)) parts.Add("War");
        if (rc.HasFlag(RequiredClass.Wizard)) parts.Add("Wiz");
        if (rc.HasFlag(RequiredClass.Taoist)) parts.Add("Tao");
        if (rc.HasFlag(RequiredClass.Assassin)) parts.Add("Ass");
        if (rc.HasFlag(RequiredClass.Archer)) parts.Add("Arc");
        return string.Join("/", parts);
    }

    private static string GetGradeClass(ItemGrade grade) => grade switch
    {
        ItemGrade.Common => "grade-common",
        ItemGrade.Rare => "grade-rare",
        ItemGrade.Legendary => "grade-legendary",
        ItemGrade.Mythical => "grade-mythical",
        ItemGrade.Heroic => "grade-heroic",
        _ => ""
    };

    private static string Esc(string s) => WebUtility.HtmlEncode(s);

    private static string GetCss() => @"
*, *::before, *::after { box-sizing: border-box; }
body {
  background: #0d1117; color: #c9d1d9;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  margin: 0; padding: 0 20px 40px;
}
h1 {
  color: #f0c040; text-align: center;
  margin: 24px 0 8px; font-size: 2em;
  text-shadow: 0 0 12px rgba(240,192,64,0.3);
}
h2 {
  color: #f0c040; border-bottom: 1px solid #30363d;
  padding: 12px 0 8px; margin: 32px 0 12px;
}
.count { color: #8b949e; font-weight: normal; font-size: 0.85em; }
nav#topnav {
  position: sticky; top: 0; z-index: 100;
  background: #0d1117ee; backdrop-filter: blur(8px);
  padding: 10px 0; border-bottom: 2px solid #f0c040;
  display: flex; flex-wrap: wrap; gap: 4px 0;
}
nav a {
  color: #f0c040; text-decoration: none;
  padding: 4px 10px; border-radius: 4px;
  font-size: 0.85em; white-space: nowrap;
}
nav a:hover { background: #1c2333; text-decoration: underline; }
nav a .count { color: #6e7681; }
.table-wrap { overflow-x: auto; }
table {
  border-collapse: collapse; width: 100%;
  margin-bottom: 8px; font-size: 0.9em;
}
th {
  background: #161b22; color: #f0c040;
  padding: 8px 10px; border: 1px solid #30363d;
  position: sticky; top: 46px; z-index: 10;
  text-align: left; white-space: nowrap;
}
td {
  padding: 5px 8px; border: 1px solid #21262d;
  vertical-align: middle; white-space: nowrap;
}
tbody tr:nth-child(even) { background: #161b22; }
tbody tr:hover { background: #1c2333; }
.icon-cell { text-align: center; padding: 2px; width: 40px; }
.item-icon {
  width: 34px; height: 34px; object-fit: contain;
  image-rendering: pixelated; display: block; margin: auto;
}
.no-icon {
  width: 34px; height: 34px; background: #21262d;
  border: 1px dashed #30363d; margin: auto;
}
td.name { font-weight: 600; }
.grade-common { color: #c9d1d9; }
.grade-rare { color: #58a6ff; }
.grade-legendary { color: #d29922; }
.grade-mythical { color: #bc4ee0; }
.grade-heroic { color: #f85149; }
footer {
  text-align: center; color: #484f58;
  padding: 24px 0; font-size: 0.8em;
}
section { max-width: 1600px; margin: 0 auto; }
";
}
